import mongoose from 'mongoose';
import dotenv from 'dotenv';
import News from './models/News';

dotenv.config();

interface NewsItem {
  title: string;
  summary: string;
  category: string;
  source: string;
  coverImage: string;
  isFeatured: boolean;
  isTrending: boolean;
  views: number;
  tags: string[];
}

const newsData: NewsItem[] = [
  // TECHNOLOGY (20)
  {
    title: 'AI Chip Redefines Data Center Performance',
    summary: 'A new AI accelerator developed by global researchers delivers massive gains in energy efficiency and speed, revolutionizing data center operations.',
    category: 'Technology',
    source: 'Tech Weekly',
    coverImage: 'https://images.unsplash.com/photo-1677442d019cecf8819246e9a87ea859?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: true,
    views: 12400,
    tags: ['AI', 'Semiconductors', 'Innovation'],
  },
  {
    title: 'Major Cybersecurity Breach Impacts Global ISPs',
    summary: 'Critical vulnerability in widely-used router firmware exposes millions of internet users to potential security threats.',
    category: 'Technology',
    source: 'Cyber Alert',
    coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 8900,
    tags: ['Cybersecurity', 'ISP', 'Vulnerability'],
  },
  {
    title: 'Quantum Computing Reaches Error-Correction Milestone',
    summary: 'Breakthrough in quantum error correction brings practical quantum computers closer to reality, with implications for cryptography and drug discovery.',
    category: 'Technology',
    source: 'Science Daily',
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e3c3136db3f0?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: false,
    views: 7600,
    tags: ['Quantum', 'Computing', 'Innovation'],
  },
  {
    title: 'New Satellite Internet Network Goes Live',
    summary: 'Global satellite internet constellation expands connectivity to remote regions, offering high-speed internet to underserved communities.',
    category: 'Technology',
    source: 'Space News',
    coverImage: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 6500,
    tags: ['Satellite', 'Internet', 'Connectivity'],
  },
  {
    title: 'Smartphone Ban Considered in European Schools',
    summary: 'European education ministers debate smartphone restrictions in classrooms to improve student focus and mental health outcomes.',
    category: 'Technology',
    source: 'Education Today',
    coverImage: 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5400,
    tags: ['Education', 'Smartphones', 'Policy'],
  },
  {
    title: 'Open-Source AI Model Rivals Proprietary Systems',
    summary: 'Community-developed AI model reaches performance parity with leading commercial systems, democratizing advanced AI technology.',
    category: 'Technology',
    source: 'AI News',
    coverImage: 'https://images.unsplash.com/photo-1677442d019cecf8819246e9a87ea859?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: true,
    views: 9200,
    tags: ['AI', 'OpenSource', 'ML'],
  },
  {
    title: 'EV Battery Breakthrough Doubles Range',
    summary: 'New solid-state battery technology achieves record energy density, potentially doubling electric vehicle driving range.',
    category: 'Technology',
    source: 'Auto Tech',
    coverImage: 'https://images.unsplash.com/photo-1559056199-641a0ac8b3f4?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 7800,
    tags: ['EV', 'Battery', 'Energy'],
  },
  {
    title: 'Global Cloud Outage Disrupts Businesses',
    summary: 'Major cloud infrastructure failure impacts millions of users worldwide, raising questions about service redundancy and reliability.',
    category: 'Technology',
    source: 'Cloud News',
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f70674e90?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4200,
    tags: ['Cloud', 'Outage', 'Infrastructure'],
  },
  {
    title: 'Neural Interface Tested in Human Trials',
    summary: 'Brain-computer interface technology shows promise in early human trials, enabling direct communication between brain and computers.',
    category: 'Technology',
    source: 'Medical Tech',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5900,
    tags: ['Neural', 'Interface', 'Medical'],
  },
  {
    title: 'Space-Based Solar Power Prototype Succeeds',
    summary: 'First demonstration of orbital solar power transmission shows feasibility of harvesting clean energy from space.',
    category: 'Technology',
    source: 'Space Tech',
    coverImage: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: false,
    views: 6800,
    tags: ['Solar', 'Space', 'Energy'],
  },
  {
    title: 'AI Regulation Framework Announced',
    summary: 'Global regulatory standards for AI development propose safety guardrails and transparency requirements for AI systems.',
    category: 'Technology',
    source: 'Policy Today',
    coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4100,
    tags: ['AI', 'Regulation', 'Policy'],
  },
  {
    title: 'Semiconductor Shortage Eases After 3 Years',
    summary: 'Global chip shortage reaches end as production capacity expands and demand normalizes across industries.',
    category: 'Technology',
    source: 'Industry News',
    coverImage: 'https://images.unsplash.com/photo-1559056199-641a0ac8b3f4?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5500,
    tags: ['Semiconductors', 'Supply', 'Manufacturing'],
  },
  {
    title: 'Robotics Startup Automates Warehouses',
    summary: 'Innovative warehouse robots increase fulfillment speed while reducing labor-intensive picking and packing operations.',
    category: 'Technology',
    source: 'Automation News',
    coverImage: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4800,
    tags: ['Robotics', 'Automation', 'Logistics'],
  },
  {
    title: 'Deepfake Detection Tool Launched',
    summary: 'Advanced AI tool successfully identifies deepfake videos with 98% accuracy, helping combat misinformation.',
    category: 'Technology',
    source: 'AI Security',
    coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 7100,
    tags: ['Deepfake', 'Detection', 'Security'],
  },
  {
    title: '6G Research Shows Early Promise',
    summary: 'Researchers achieve first 6G transmission, demonstrating speeds 100 times faster than current 5G networks.',
    category: 'Technology',
    source: 'Telecom Journal',
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f70674e90?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3900,
    tags: ['6G', 'Wireless', 'Technology'],
  },
  {
    title: 'Autonomous Cargo Ships Begin Trials',
    summary: 'First commercially viable autonomous cargo vessel completes successful sea trial, reducing shipping costs significantly.',
    category: 'Technology',
    source: 'Maritime News',
    coverImage: 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4600,
    tags: ['Autonomous', 'Shipping', 'AI'],
  },
  {
    title: 'Data Privacy Laws Tightened Worldwide',
    summary: 'New international data protection standards impose stricter requirements on tech companies handling user information.',
    category: 'Technology',
    source: 'Privacy News',
    coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3400,
    tags: ['Privacy', 'Data', 'Regulation'],
  },
  {
    title: 'New Programming Language Gains Adoption',
    summary: 'Modern programming language designed for safety and performance gains rapid adoption among developers.',
    category: 'Technology',
    source: 'Dev News',
    coverImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3100,
    tags: ['Programming', 'Language', 'Development'],
  },
  {
    title: 'Tech Giants Invest in Clean Energy AI',
    summary: 'Major technology companies pledge billions to develop AI systems optimizing renewable energy grids.',
    category: 'Technology',
    source: 'Green Tech',
    coverImage: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: false,
    views: 6300,
    tags: ['AI', 'Energy', 'Sustainability'],
  },
  {
    title: 'Supercomputer Breaks Climate Modeling Records',
    summary: 'Next-generation supercomputer enables unprecedented climate simulations with atom-level accuracy for better predictions.',
    category: 'Technology',
    source: 'Climate News',
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e3c3136db3f0?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5200,
    tags: ['Supercomputer', 'Climate', 'Computing'],
  },

  // BUSINESS (20)
  {
    title: 'Global Markets Rally on Inflation Slowdown',
    summary: 'Stock markets surge worldwide as inflation rates decline, raising investor confidence in economic recovery.',
    category: 'Business',
    source: 'Financial Times',
    coverImage: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f629?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: true,
    views: 11200,
    tags: ['Markets', 'Economy', 'Inflation'],
  },
  {
    title: 'Major Bank Announces Digital-Only Expansion',
    summary: 'Leading financial institution launches new digital-only subsidiary targeting younger demographic with app-based services.',
    category: 'Business',
    source: 'Banking News',
    coverImage: 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4700,
    tags: ['Banking', 'Digital', 'Finance'],
  },
  {
    title: 'Startup Valuations Stabilize After Correction',
    summary: 'Venture capital market shows signs of stabilization after period of aggressive devaluation in startup sector.',
    category: 'Business',
    source: 'VC News',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3800,
    tags: ['Startups', 'Valuation', 'Investment'],
  },
  {
    title: 'Oil Prices Fall Amid Supply Increase',
    summary: 'Crude oil prices decline as OPEC nations increase production, easing global energy cost pressures.',
    category: 'Business',
    source: 'Energy Markets',
    coverImage: 'https://images.unsplash.com/photo-1635373379348-dca6b5bf9b10?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5600,
    tags: ['Oil', 'Energy', 'Commodities'],
  },
  {
    title: 'EV Sales Overtake Petrol Cars in Europe',
    summary: 'Electric vehicle sales surpass traditional gasoline car sales for first time in European market history.',
    category: 'Business',
    source: 'Auto Industry',
    coverImage: 'https://images.unsplash.com/photo-1560958089-b8a63395bbf1?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: true,
    views: 8400,
    tags: ['EV', 'Automotive', 'Sales'],
  },
  {
    title: 'Retail Giant Shuts 300 Stores',
    summary: 'Major department store chain announces massive store closure as it shifts focus to e-commerce operations.',
    category: 'Business',
    source: 'Retail News',
    coverImage: 'https://images.unsplash.com/photo-1556741533-b48f80c8f7dc?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4300,
    tags: ['Retail', 'E-commerce', 'Business'],
  },
  {
    title: 'Crypto Market Sees Regulatory Relief',
    summary: 'New regulatory framework provides clarity for cryptocurrency exchanges, sparking investor confidence recovery.',
    category: 'Business',
    source: 'Crypto News',
    coverImage: 'https://images.unsplash.com/photo-1621761191007-11ae4a7a7644?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 6800,
    tags: ['Crypto', 'Regulation', 'Finance'],
  },
  {
    title: 'Manufacturing Shifts Back to Asia',
    summary: 'Global manufacturing gradually returns to Asian facilities after supply chain diversification experiments.',
    category: 'Business',
    source: 'Manufacturing Weekly',
    coverImage: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3500,
    tags: ['Manufacturing', 'Supply Chain', 'Global'],
  },
  {
    title: 'Airline Industry Posts Record Profits',
    summary: 'Airlines report strongest quarterly earnings in history driven by post-pandemic travel demand surge.',
    category: 'Business',
    source: 'Travel Industry',
    coverImage: 'https://images.unsplash.com/photo-1556389179-a6fa6472e558?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 5400,
    tags: ['Airlines', 'Travel', 'Revenue'],
  },
  {
    title: 'E-commerce Growth Slows Post-Boom',
    summary: 'Online retail growth decelerates as in-store shopping rebounds and market saturation increases.',
    category: 'Business',
    source: 'Retail Report',
    coverImage: 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4100,
    tags: ['E-commerce', 'Retail', 'Growth'],
  },
  {
    title: 'New Trade Agreement Signed',
    summary: 'Major international trade deal reduces tariffs and opens new market opportunities for member nations.',
    category: 'Business',
    source: 'Trade News',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3200,
    tags: ['Trade', 'Agreement', 'International'],
  },
  {
    title: 'Gold Prices Hit All-Time High',
    summary: 'Gold prices reach record levels driven by geopolitical tensions and currency weakening concerns.',
    category: 'Business',
    source: 'Commodities',
    coverImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4900,
    tags: ['Gold', 'Commodities', 'Investment'],
  },
  {
    title: 'IPO Market Reopens Strongly',
    summary: 'Initial public offerings surge after period of corporate caution, attracting major investment inflows.',
    category: 'Business',
    source: 'Markets Daily',
    coverImage: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f629?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3700,
    tags: ['IPO', 'Markets', 'Finance'],
  },
  {
    title: 'Logistics Costs Drop Sharply',
    summary: 'Global shipping rates decline as cargo volumes normalize and port congestion eases worldwide.',
    category: 'Business',
    source: 'Logistics News',
    coverImage: 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3400,
    tags: ['Logistics', 'Shipping', 'Supply Chain'],
  },
  {
    title: 'Small Businesses Embrace AI Tools',
    summary: 'SMEs increasingly adopt artificial intelligence for automation, boosting productivity and reducing operational costs.',
    category: 'Business',
    source: 'Business Journal',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: false,
    views: 5100,
    tags: ['SME', 'AI', 'Technology'],
  },
  {
    title: 'Real Estate Demand Rebounds',
    summary: 'Property markets recover strongly as interest rates stabilize and buyer confidence returns.',
    category: 'Business',
    source: 'Property Market',
    coverImage: 'https://images.unsplash.com/photo-1560607592-735dac1d127f?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4200,
    tags: ['Real Estate', 'Property', 'Market'],
  },
  {
    title: 'Banking Sector Faces Cyber Risks',
    summary: 'Financial institutions increase security spending amid rising sophistication of cyber attacks targeting banking systems.',
    category: 'Business',
    source: 'Finance Security',
    coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3900,
    tags: ['Banking', 'Cybersecurity', 'Risk'],
  },
  {
    title: 'Consumer Spending Shows Resilience',
    summary: 'Retail sales remain strong despite economic headwinds, indicating sustained consumer confidence.',
    category: 'Business',
    source: 'Economics Daily',
    coverImage: 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 4600,
    tags: ['Retail', 'Consumer', 'Economy'],
  },
  {
    title: 'Fintech Lending Rules Updated',
    summary: 'Regulatory bodies establish new frameworks for fintech lending platforms to ensure consumer protection.',
    category: 'Business',
    source: 'Fintech News',
    coverImage: 'https://images.unsplash.com/photo-1556667355-d4fcf00fcd50?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 2800,
    tags: ['Fintech', 'Lending', 'Regulation'],
  },
  {
    title: 'Corporate Layoffs Decline Quarter-on-Quarter',
    summary: 'Technology sector employment stabilizes as mass layoff trend reverses and hiring resumes.',
    category: 'Business',
    source: 'Jobs Market',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3600,
    tags: ['Employment', 'HR', 'Economy'],
  },

  // SCIENCE (20)
  {
    title: 'Climate Models Predict Faster Ice Melt',
    summary: 'Latest climate simulations indicate accelerated Arctic ice loss threatens coastal regions with rising sea levels.',
    category: 'Science',
    source: 'Nature Reports',
    coverImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: true,
    views: 9800,
    tags: ['Climate', 'Arctic', 'Environment'],
  },
  {
    title: 'New Exoplanet Found in Habitable Zone',
    summary: 'Astronomers discover potentially habitable Earth-like exoplanet orbiting nearby star system.',
    category: 'Science',
    source: 'Space Journal',
    coverImage: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 10200,
    tags: ['Astronomy', 'Exoplanet', 'Space'],
  },
  {
    title: 'Fusion Reactor Sets Energy Record',
    summary: 'Nuclear fusion experiment achieves breakthrough in sustained energy output, advancing clean energy technology.',
    category: 'Science',
    source: 'Energy Science',
    coverImage: 'https://images.unsplash.com/photo-1533001971828-4ab89ad00120?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: true,
    views: 8600,
    tags: ['Fusion', 'Energy', 'Research'],
  },
  {
    title: 'Scientists Reverse Cellular Aging in Mice',
    summary: 'Researchers successfully reverse age-related cellular changes in laboratory mice, opening possibilities for aging therapies.',
    category: 'Science',
    source: 'Biology Today',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 7400,
    tags: ['Aging', 'Biology', 'Medicine'],
  },
  {
    title: 'Ocean Mapping Reveals New Species',
    summary: 'Deep sea exploration uncovers thousands of previously unknown marine species in abyssal trenches.',
    category: 'Science',
    source: 'Marine Science',
    coverImage: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 6500,
    tags: ['Ocean', 'Marine', 'Biodiversity'],
  },
  {
    title: 'Mars Rover Finds Organic Compounds',
    summary: 'NASA rover discovers organic molecules in Martian soil, suggesting possible past or present microbial life.',
    category: 'Science',
    source: 'Space Exploration',
    coverImage: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: true,
    views: 11500,
    tags: ['Mars', 'Astrobiology', 'Exploration'],
  },
  {
    title: 'Gene Editing Treats Rare Disease',
    summary: 'First successful CRISPR gene therapy treats previously untreatable genetic disorder in human patients.',
    category: 'Science',
    source: 'Medical Science',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 7100,
    tags: ['Gene Therapy', 'CRISPR', 'Medicine'],
  },
  {
    title: 'Space Telescope Captures Early Galaxies',
    summary: 'James Webb Space Telescope reveals first galaxies formed shortly after Big Bang, revolutionizing cosmology.',
    category: 'Science',
    source: 'Astronomy Today',
    coverImage: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 6200,
    tags: ['Telescope', 'Astronomy', 'Cosmology'],
  },
  {
    title: 'Volcano Monitoring Prevents Disaster',
    summary: 'Advanced monitoring system successfully predicts volcanic eruption, enabling timely evacuation of 50,000 residents.',
    category: 'Science',
    source: 'Geology News',
    coverImage: 'https://images.unsplash.com/photo-1578922754883-1e2a5f9b0f09?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5800,
    tags: ['Volcano', 'Disaster', 'Geology'],
  },
  {
    title: 'Earthquake Prediction Improves',
    summary: 'Machine learning algorithms enhance earthquake prediction accuracy, providing better early warning systems.',
    category: 'Science',
    source: 'Seismology Journal',
    coverImage: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b6?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4700,
    tags: ['Earthquake', 'Prediction', 'AI'],
  },
  {
    title: 'New Vaccine Platform Developed',
    summary: 'Revolutionary vaccine technology platform shows promise against multiple diseases including cancer.',
    category: 'Science',
    source: 'Immunology Today',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 6900,
    tags: ['Vaccine', 'Medicine', 'Immunology'],
  },
  {
    title: 'AI Helps Decode Brain Signals',
    summary: 'Artificial intelligence successfully interprets brain signals for thought-reading application in paralyzed patients.',
    category: 'Science',
    source: 'Neuroscience News',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 7600,
    tags: ['Brain', 'AI', 'Neuroscience'],
  },
  {
    title: 'Antarctic Ice Shelf Collapse Studied',
    summary: 'Scientists analyze largest Antarctic ice shelf collapse in recent history, attributing changes to climate warming.',
    category: 'Science',
    source: 'Climate Research',
    coverImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5400,
    tags: ['Antarctica', 'Ice', 'Climate'],
  },
  {
    title: 'Asteroid Deflection Test Successful',
    summary: 'DART mission successfully alters asteroid trajectory, proving planetary defense technology viable.',
    category: 'Science',
    source: 'Space Agency News',
    coverImage: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: false,
    views: 8200,
    tags: ['Asteroid', 'Defense', 'Space'],
  },
  {
    title: 'Renewable Energy Efficiency Breakthrough',
    summary: 'Solar panel efficiency reaches 50% through multi-junction cell technology innovation.',
    category: 'Science',
    source: 'Energy Research',
    coverImage: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5600,
    tags: ['Solar', 'Energy', 'Innovation'],
  },
  {
    title: 'Microplastics Found in Clouds',
    summary: 'Researchers discover microplastics in cloud formations affecting weather patterns and precipitation.',
    category: 'Science',
    source: 'Atmospheric Science',
    coverImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4200,
    tags: ['Plastics', 'Environment', 'Atmosphere'],
  },
  {
    title: 'New Periodic Table Expansion Proposed',
    summary: 'Scientists propose addition of new superheavy elements to periodic table based on recent discoveries.',
    category: 'Science',
    source: 'Chemistry Journal',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3800,
    tags: ['Chemistry', 'Elements', 'Science'],
  },
  {
    title: 'Solar Storm Warning Issued',
    summary: 'Massive solar storm threatens communication and power systems; emergency preparedness measures activated.',
    category: 'Science',
    source: 'Space Weather',
    coverImage: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 6700,
    tags: ['Solar', 'Storm', 'Space'],
  },
  {
    title: 'Atmospheric CO₂ Peaks Again',
    summary: 'Carbon dioxide levels reach new historical high despite emission reduction efforts worldwide.',
    category: 'Science',
    source: 'Climate News',
    coverImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4900,
    tags: ['CO2', 'Climate', 'Environment'],
  },
  {
    title: 'Biodiversity Loss Accelerates',
    summary: 'Global species extinction rates accelerate five times faster than historical background rates.',
    category: 'Science',
    source: 'Conservation Today',
    coverImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5100,
    tags: ['Biodiversity', 'Conservation', 'Environment'],
  },

  // WORLD (20)
  {
    title: 'Peace Talks Resume After Ceasefire',
    summary: 'International mediators restart peace negotiations following historic ceasefire agreement between conflicting nations.',
    category: 'World',
    source: 'Global News',
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: true,
    views: 13400,
    tags: ['Peace', 'Diplomacy', 'Conflict'],
  },
  {
    title: 'Massive Protests Erupt Over Reforms',
    summary: 'Large-scale demonstrations across multiple cities against proposed government reforms.',
    category: 'World',
    source: 'World News',
    coverImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 10100,
    tags: ['Protest', 'Politics', 'Society'],
  },
  {
    title: 'Floods Displace Millions in Asia',
    summary: 'Unprecedented flooding across multiple Asian countries displaces millions and causes widespread devastation.',
    category: 'World',
    source: 'Disaster News',
    coverImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: true,
    views: 11600,
    tags: ['Floods', 'Disaster', 'Asia'],
  },
  {
    title: 'Election Results Trigger Market Reaction',
    summary: 'Election outcome causes significant volatility in global financial markets and currency exchanges.',
    category: 'World',
    source: 'Politics Daily',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 6200,
    tags: ['Election', 'Politics', 'Markets'],
  },
  {
    title: 'Border Tensions Ease After Talks',
    summary: 'Neighboring countries de-escalate border dispute through diplomatic negotiations and confidence-building measures.',
    category: 'World',
    source: 'International Report',
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5400,
    tags: ['Diplomacy', 'Border', 'Relations'],
  },
  {
    title: 'Refugee Crisis Worsens',
    summary: 'Record numbers of refugees flee conflict zones, overwhelming international humanitarian systems.',
    category: 'World',
    source: 'Humanitarian News',
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 7900,
    tags: ['Refugee', 'Crisis', 'Humanitarian'],
  },
  {
    title: 'Global Summit Addresses Climate Crisis',
    summary: 'World leaders gather to forge new commitments on climate change mitigation and adaptation strategies.',
    category: 'World',
    source: 'Climate Talks',
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: true,
    views: 8800,
    tags: ['Climate', 'Summit', 'Environment'],
  },
  {
    title: 'Military Coup Attempt Fails',
    summary: 'Failed military coup attempt in African nation results in strengthened democratic institutions.',
    category: 'World',
    source: 'Political News',
    coverImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5100,
    tags: ['Politics', 'Coup', 'Africa'],
  },
  {
    title: 'Sanctions Lifted After Agreement',
    summary: 'International economic sanctions removed following agreement on nuclear program and human rights improvements.',
    category: 'World',
    source: 'Diplomatic News',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4600,
    tags: ['Sanctions', 'Diplomacy', 'International'],
  },
  {
    title: 'Earthquake Hits Coastal Region',
    summary: 'Powerful earthquake strikes coastal area, triggering tsunami warnings and emergency response operations.',
    category: 'World',
    source: 'Disaster Report',
    coverImage: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b6?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 6800,
    tags: ['Earthquake', 'Disaster', 'Emergency'],
  },
  {
    title: 'International Court Issues Ruling',
    summary: 'Global court pronounces judgment in high-profile international case with implications for international law.',
    category: 'World',
    source: 'Legal News',
    coverImage: 'https://images.unsplash.com/photo-1534773869737-41e11183f7b8?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4200,
    tags: ['Court', 'Justice', 'Law'],
  },
  {
    title: 'Energy Crisis Deepens in Europe',
    summary: 'European energy crisis intensifies as winter approaches and supply constraints persist.',
    category: 'World',
    source: 'Energy News',
    coverImage: 'https://images.unsplash.com/photo-1633373379348-dca6b5bf9b10?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5800,
    tags: ['Energy', 'Crisis', 'Europe'],
  },
  {
    title: 'Humanitarian Aid Blocked',
    summary: 'Aid organizations report blockade preventing delivery of humanitarian assistance to affected populations.',
    category: 'World',
    source: 'Humanitarian Report',
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4900,
    tags: ['Humanitarian', 'Aid', 'Crisis'],
  },
  {
    title: 'Cyber Warfare Escalates',
    summary: 'Nations engage in unprecedented cyber attacks targeting critical infrastructure and government systems.',
    category: 'World',
    source: 'Security Report',
    coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 6300,
    tags: ['Cyber', 'Warfare', 'Security'],
  },
  {
    title: 'New Alliance Formed',
    summary: 'Several nations establish military and economic alliance to strengthen regional cooperation and stability.',
    category: 'World',
    source: 'Political Alliance',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3900,
    tags: ['Alliance', 'International', 'Cooperation'],
  },
  {
    title: 'Food Shortages Rise',
    summary: 'Global food shortages intensify affecting vulnerable populations across multiple continents.',
    category: 'World',
    source: 'Food Security',
    coverImage: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 7200,
    tags: ['Food', 'Crisis', 'Security'],
  },
  {
    title: 'Diplomatic Relations Restored',
    summary: 'Two countries restore full diplomatic relations after decades of tensions through negotiated settlement.',
    category: 'World',
    source: 'Diplomacy News',
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3700,
    tags: ['Diplomacy', 'Relations', 'Peace'],
  },
  {
    title: 'Internet Shutdowns Spark Backlash',
    summary: 'Government-imposed internet outages trigger international condemnation and human rights concerns.',
    category: 'World',
    source: 'Digital Rights',
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f70674e90?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4400,
    tags: ['Internet', 'Freedom', 'Rights'],
  },
  {
    title: 'Currency Crisis Hits Developing Nation',
    summary: 'Severe currency devaluation creates economic crisis affecting millions in developing country.',
    category: 'World',
    source: 'Economic Crisis',
    coverImage: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f629?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5300,
    tags: ['Currency', 'Crisis', 'Economy'],
  },
  {
    title: 'UN Issues Global Warning',
    summary: 'United Nations releases urgent report warning of global challenges requiring immediate international action.',
    category: 'World',
    source: 'UN News',
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4100,
    tags: ['UN', 'Global', 'Warning'],
  },

  // HEALTH (20)
  {
    title: 'New Study Links Sleep to Longevity',
    summary: 'Research reveals strong correlation between quality sleep patterns and increased lifespan and health outcomes.',
    category: 'Health',
    source: 'Health Weekly',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: true,
    views: 12100,
    tags: ['Sleep', 'Health', 'Longevity'],
  },
  {
    title: 'Pandemic Preparedness Plan Updated',
    summary: 'World Health Organization releases comprehensive pandemic preparedness guidelines for global health security.',
    category: 'Health',
    source: 'WHO News',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5600,
    tags: ['Pandemic', 'Health', 'Preparedness'],
  },
  {
    title: 'Mental Health Cases Rise Globally',
    summary: 'Global mental health crisis escalates with rising depression and anxiety cases across all demographics.',
    category: 'Health',
    source: 'Mental Health Today',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 8900,
    tags: ['Mental Health', 'Crisis', 'Wellness'],
  },
  {
    title: 'Cancer Detection AI Approved',
    summary: 'FDA approves artificial intelligence system for early cancer detection with superior accuracy rates.',
    category: 'Health',
    source: 'Medical News',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: true,
    isTrending: true,
    views: 9700,
    tags: ['Cancer', 'AI', 'Medical'],
  },
  {
    title: 'Antibiotic Resistance Warning Issued',
    summary: 'WHO warns of dangerous antibiotic-resistant bacteria spreading globally, threatening modern medicine.',
    category: 'Health',
    source: 'Health Alert',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 6300,
    tags: ['Antibiotic', 'Resistance', 'Medicine'],
  },
  {
    title: 'Air Pollution Impacts Heart Health',
    summary: 'New study demonstrates direct link between air pollution exposure and increased cardiovascular disease risk.',
    category: 'Health',
    source: 'Environmental Health',
    coverImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5200,
    tags: ['Pollution', 'Heart', 'Health'],
  },
  {
    title: 'New Diabetes Drug Approved',
    summary: 'Revolutionary diabetes treatment approved offering improved blood sugar control with minimal side effects.',
    category: 'Health',
    source: 'Pharma News',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4800,
    tags: ['Diabetes', 'Medicine', 'Treatment'],
  },
  {
    title: 'Heatwaves Increase Mortality Risk',
    summary: 'Rising global temperatures cause dangerous heatwaves increasing mortality rates particularly among elderly.',
    category: 'Health',
    source: 'Climate Health',
    coverImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 6700,
    tags: ['Heat', 'Climate', 'Health'],
  },
  {
    title: 'Nutrition Guidelines Revised',
    summary: 'Leading health organizations update dietary recommendations based on latest nutritional science research.',
    category: 'Health',
    source: 'Nutrition Journal',
    coverImage: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4100,
    tags: ['Nutrition', 'Diet', 'Health'],
  },
  {
    title: 'Global Vaccination Rates Improve',
    summary: 'Worldwide vaccination coverage increases reaching new historic highs against major infectious diseases.',
    category: 'Health',
    source: 'Vaccination News',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5900,
    tags: ['Vaccination', 'Health', 'Immunization'],
  },
  {
    title: 'Obesity Trends Stabilize',
    summary: 'Global obesity rates show signs of stabilization through improved public health interventions.',
    category: 'Health',
    source: 'Health Report',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3900,
    tags: ['Obesity', 'Health', 'Wellness'],
  },
  {
    title: 'Hospital Cyberattack Disrupts Care',
    summary: 'Major hospital network falls victim to ransomware attack disrupting patient care services.',
    category: 'Health',
    source: 'Healthcare Security',
    coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4300,
    tags: ['Cyberattack', 'Hospital', 'Security'],
  },
  {
    title: 'Rare Virus Contained',
    summary: 'Health authorities successfully contain outbreak of rare infectious virus preventing widespread transmission.',
    category: 'Health',
    source: 'Disease Control',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3600,
    tags: ['Virus', 'Outbreak', 'Health'],
  },
  {
    title: 'Aging Population Strains Systems',
    summary: 'Rapidly aging global population creates significant strain on healthcare and pension systems worldwide.',
    category: 'Health',
    source: 'Healthcare Policy',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4600,
    tags: ['Aging', 'Healthcare', 'Society'],
  },
  {
    title: 'Fitness Tracking Data Insights Released',
    summary: 'Analysis of billions of fitness tracking data points reveals population health trends and patterns.',
    category: 'Health',
    source: 'Fitness News',
    coverImage: 'https://images.unsplash.com/photo-1552821206-0bdf466b8794?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3400,
    tags: ['Fitness', 'Health', 'Data'],
  },
  {
    title: 'Gut Microbiome Breakthrough',
    summary: 'Researchers discover critical role of gut bacteria in preventing autoimmune diseases.',
    category: 'Health',
    source: 'Medical Research',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 5100,
    tags: ['Microbiome', 'Immune', 'Health'],
  },
  {
    title: 'New Alzheimer\'s Therapy Trial',
    summary: 'Clinical trial shows promising results for experimental Alzheimer\'s disease treatment.',
    category: 'Health',
    source: 'Neurology Today',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4700,
    tags: ['Alzheimer', 'Treatment', 'Medicine'],
  },
  {
    title: 'Medical Staff Shortage Grows',
    summary: 'Healthcare systems face critical shortage of medical professionals affecting patient care quality.',
    category: 'Health',
    source: 'Healthcare News',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 3800,
    tags: ['Healthcare', 'Shortage', 'Workforce'],
  },
  {
    title: 'Telemedicine Adoption Expands',
    summary: 'Remote healthcare services continue rapid expansion improving medical access in underserved areas.',
    category: 'Health',
    source: 'Health Tech',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: true,
    views: 5400,
    tags: ['Telemedicine', 'Healthcare', 'Technology'],
  },
  {
    title: 'WHO Issues Health Advisory',
    summary: 'World Health Organization issues urgent health advisory regarding emerging health threat.',
    category: 'Health',
    source: 'WHO Advisory',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-112173f1dd00?w=800&h=400&fit=crop',
    isFeatured: false,
    isTrending: false,
    views: 4200,
    tags: ['WHO', 'Health', 'Advisory'],
  },
];

async function seedDatabase() {
  try {
    const mongoUri = process.env.MONGODB_URI;
    if (!mongoUri) {
      throw new Error('MONGODB_URI is not set');
    }

    await mongoose.connect(mongoUri);
    console.log('✅ Connected to MongoDB');

    // Clear existing news
    await News.deleteMany({});
    console.log('🗑️  Cleared existing news');

    // Insert new data
    const result = await News.insertMany(newsData);
    console.log(`✅ Seeded ${result.length} news articles`);

    await mongoose.connection.close();
    console.log('✅ Database seeding completed successfully');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error);
    process.exit(1);
  }
}

seedDatabase();
